# Generated by Django 5.2.17 on 2026-08-20 00:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pengguna', 'Pengguna')], default='pengguna', max_length=20)),
                ('token_akses', models.CharField(default=core.models.buat_token, max_length=64, unique=True)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'm_pengguna',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('sektoral', 'Sektoral (Lapangan Usaha)'), ('pengeluaran', 'Pengeluaran')], max_length=15)),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=150)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori PDRB',
                'verbose_name_plural': 'Kategori PDRB',
                'db_table': 'm_kategori',
                'ordering': ['jenis', 'urutan'],
                'constraints': [models.UniqueConstraint(fields=('jenis', 'kode'), name='uniq_jenis_kode')],
            },
        ),
        migrations.CreateModel(
            name='KataKunci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_kunci', models.CharField(max_length=100)),
                ('bobot', models.PositiveSmallIntegerField(default=1)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kata_kunci', to='core.kategori')),
            ],
            options={
                'verbose_name': 'Kata Kunci',
                'verbose_name_plural': 'Kata Kunci',
                'db_table': 'm_kata_kunci',
                'ordering': ['kategori', 'kata_kunci'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('triwulan', models.PositiveSmallIntegerField(help_text='1-4 untuk triwulanan, 0 untuk periode tahunan')),
                ('nama_periode', models.CharField(max_length=30)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tutup', 'Tutup')], default='aktif', max_length=15)),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Periode',
                'db_table': 'm_periode',
                'ordering': ['-tahun', '-triwulan'],
                'constraints': [models.UniqueConstraint(fields=('tahun', 'triwulan'), name='uniq_tahun_triwulan')],
            },
        ),
    ]
