# Generated by Django 5.2.17 on 2026-09-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kategori_induk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='catatan',
            field=models.TextField(blank=True, help_text='Ditampilkan bila komponen belum/tidak memiliki indikator'),
        ),
    ]
