# Generated by Django 5.2.17 on 2026-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kategori_catatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='id_template',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nilai kolom id_komponen pada template provinsi', null=True, verbose_name='id_komponen template'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='kode_template',
            field=models.CharField(blank=True, help_text='Nilai kolom No pada template, contoh: A. 1. a.', max_length=30, verbose_name='Kode pada template'),
        ),
    ]
