# Generated by Django 5.2.17 on 2026-09-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kategori_id_template_kategori_kode_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='akses_permanen',
            field=models.BooleanField(default=False, help_text='Pengelola sistem yang dapat mengakses dari perangkat mana pun tanpa membuka tautan token. Berikan hanya kepada satu orang.', verbose_name='Akses tanpa token'),
        ),
    ]
