# Generated by Django 5.2.17 on 2026-09-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pengguna_akses_permanen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='akun',
            field=models.OneToOneField(blank=True, help_text='Ditautkan hanya untuk pengguna berakses permanen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Akun pengelola'),
        ),
    ]
