# Generated by Django 5.2.17 on 2026-09-13 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pengguna_akun'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=30)),
                ('entitas', models.CharField(blank=True, max_length=50)),
                ('entitas_id', models.BigIntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('waktu', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alamat_ip', models.CharField(blank=True, max_length=45)),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitas', to='core.pengguna')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'db_table': 't_log_aktivitas',
                'ordering': ['-waktu'],
            },
        ),
    ]
