# Generated by Django 5.2.17 on 2026-08-20 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_portal', models.CharField(max_length=100)),
                ('url_dasar', models.URLField(max_length=255)),
                ('url_sumber', models.URLField(help_text='Alamat RSS atau halaman indeks', max_length=255)),
                ('tipe_sumber', models.CharField(choices=[('rss', 'RSS Feed'), ('html', 'Halaman HTML')], default='rss', max_length=10)),
                ('konfigurasi', models.JSONField(blank=True, help_text='Selector untuk tipe HTML', null=True)),
                ('jeda_detik', models.PositiveSmallIntegerField(default=2)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Portal Berita',
                'verbose_name_plural': 'Portal Berita',
                'db_table': 'm_portal',
                'ordering': ['nama_portal'],
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('tanggal_berita', models.DateField(db_index=True)),
                ('ringkasan', models.TextField(blank=True)),
                ('jenis_dampak', models.CharField(blank=True, choices=[('ntb', 'NTB'), ('harga', 'Harga')], max_length=15)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('terverifikasi', 'Terverifikasi'), ('ditolak', 'Ditolak')], db_index=True, default='baru', max_length=20)),
                ('hash_konten', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sumber_input', models.CharField(choices=[('scraping', 'Scraping'), ('manual', 'Manual')], default='scraping', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to='core.pengguna')),
                ('periode', models.ForeignKey(blank=True, help_text='Kosongkan bila berita tidak masuk periode mana pun (Lainnya)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='berita', to='core.periode')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'db_table': 't_berita',
                'ordering': ['-tanggal_berita', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BeritaKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arah_dampak', models.CharField(blank=True, choices=[('meningkatkan', 'Meningkatkan'), ('menurunkan', 'Menurunkan'), ('netral', 'Netral')], max_length=15)),
                ('skor_otomatis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.berita')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.kategori')),
            ],
            options={
                'verbose_name': 'Kategori Berita',
                'verbose_name_plural': 'Kategori Berita',
                'db_table': 'r_berita_kategori',
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ManyToManyField(blank=True, related_name='berita', through='berita.BeritaKategori', to='core.kategori'),
        ),
        migrations.CreateModel(
            name='LogScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('jumlah_ditemukan', models.IntegerField(default=0)),
                ('jumlah_disimpan', models.IntegerField(default=0)),
                ('jumlah_duplikat', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('sukses', 'Sukses'), ('sebagian', 'Sebagian'), ('gagal', 'Gagal')], max_length=15)),
                ('pesan', models.TextField(blank=True)),
                ('dijalankan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pengguna')),
                ('portal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='berita.portal')),
            ],
            options={
                'verbose_name': 'Log Scraping',
                'verbose_name_plural': 'Log Scraping',
                'db_table': 't_log_scraping',
                'ordering': ['-waktu_mulai'],
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to='berita.portal'),
        ),
        migrations.AddConstraint(
            model_name='beritakategori',
            constraint=models.UniqueConstraint(fields=('berita', 'kategori'), name='uniq_berita_kategori'),
        ),
        migrations.AddIndex(
            model_name='berita',
            index=models.Index(fields=['periode', 'status'], name='idx_berita_periode'),
        ),
    ]
