# Generated by Django 5.2.17 on 2026-08-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='jenis_dampak',
        ),
        migrations.AddField(
            model_name='berita',
            name='dampak',
            field=models.CharField(blank=True, choices=[('meningkatkan_ntb', 'Meningkatkan NTB'), ('menurunkan_ntb', 'Menurunkan NTB'), ('meningkatkan_harga', 'Meningkatkan Harga'), ('menurunkan_harga', 'Menurunkan Harga')], db_index=True, max_length=25),
        ),
    ]
