# Generated by Django 5.2.17 on 2026-08-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_remove_berita_jenis_dampak_berita_dampak'),
    ]

    operations = [
        migrations.AddField(
            model_name='logscraping',
            name='jumlah_diabaikan',
            field=models.IntegerField(default=0, verbose_name='Di luar wilayah'),
        ),
        migrations.AddField(
            model_name='portal',
            name='filter_wilayah',
            field=models.CharField(blank=True, default='malinau,kalimantan utara,kaltara', help_text='Kata kunci wilayah dipisah koma. Berita yang tidak memuat salah satunya akan diabaikan. Kosongkan untuk menerima semua berita.', max_length=255),
        ),
    ]
