# Generated by Django 5.2.17 on 2026-08-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_logscraping_jumlah_diabaikan_portal_filter_wilayah'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='lingkup',
            field=models.CharField(choices=[('malinau', 'Malinau'), ('kaltara', 'Kaltara'), ('lainnya', 'Lainnya')], db_index=True, default='lainnya', help_text='Malinau diprioritaskan; Kaltara dipakai bila kategori belum ada beritanya', max_length=15),
        ),
    ]
