# Generated by Django 5.2.17 on 2026-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_berita_lingkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='penerbit',
            field=models.CharField(blank=True, help_text='Nama media asal, terisi otomatis untuk feed agregator', max_length=100),
        ),
    ]
