# Generated by Django 5.2.17 on 2026-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_berita_penerbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='tanggal_peristiwa',
            field=models.DateField(blank=True, db_index=True, help_text='Tanggal kejadian yang disebut di dalam berita. Kosongkan bila sama dengan tanggal terbit.', null=True, verbose_name='Tanggal peristiwa'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal_berita',
            field=models.DateField(db_index=True, verbose_name='Tanggal terbit'),
        ),
    ]
