# Generated by Django 5.2.17 on 2026-09-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_berita_tanggal_peristiwa_alter_berita_tanggal_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetODON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Sheet ODON', max_length=100)),
                ('id_spreadsheet', models.CharField(max_length=100)),
                ('gid_sheet', models.CharField(default='0', max_length=30, verbose_name='GID sheet')),
                ('nama_tab', models.CharField(help_text='Nama tab, contoh: 2026', max_length=50)),
                ('baris_pertama', models.PositiveSmallIntegerField(default=6)),
                ('kol_tanggal', models.PositiveSmallIntegerField(default=2, verbose_name='Kolom waktu input')),
                ('kol_judul', models.PositiveSmallIntegerField(default=3)),
                ('kol_kategori', models.PositiveSmallIntegerField(default=4)),
                ('kol_ringkasan', models.PositiveSmallIntegerField(default=5)),
                ('kol_dampak', models.PositiveSmallIntegerField(default=6)),
                ('kol_sumber', models.PositiveSmallIntegerField(default=7)),
                ('kol_periode', models.PositiveSmallIntegerField(default=8)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sheet ODON',
                'verbose_name_plural': 'Sheet ODON',
                'db_table': 'm_sheet_odon',
            },
        ),
    ]
