# Generated by Django 5.2.17 on 2026-09-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('berita', '0005_berita_penerbit'),
        ('core', '0004_kategori_id_template_kategori_kode_template'),
        ('inventarisasi', '0004_alter_opd_options_alter_opd_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disusun_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pengguna')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fenomena', to='core.kategori')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fenomena', to='core.periode')),
            ],
            options={
                'verbose_name': 'Fenomena',
                'verbose_name_plural': 'Fenomena',
                'db_table': 't_fenomena',
                'ordering': ['periode', 'kategori__urutan'],
            },
        ),
        migrations.CreateModel(
            name='FenomenaBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(blank=True, help_text='Kosongkan bila berlaku untuk semua jenis pertumbuhan', max_length=10)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('kutipan', models.TextField(blank=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.berita')),
                ('fenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fenomena.fenomena')),
            ],
            options={
                'verbose_name': 'Berita Fenomena',
                'verbose_name_plural': 'Berita Fenomena',
                'db_table': 'r_fenomena_berita',
            },
        ),
        migrations.CreateModel(
            name='FenomenaIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(blank=True, max_length=10)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('catatan', models.TextField(blank=True)),
                ('fenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fenomena.fenomena')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarisasi.indikator')),
            ],
            options={
                'verbose_name': 'Indikator Fenomena',
                'verbose_name_plural': 'Indikator Fenomena',
                'db_table': 'r_fenomena_indikator',
            },
        ),
        migrations.CreateModel(
            name='FenomenaRincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('qtoq', 'q-to-q'), ('yoy', 'y-o-y'), ('ctoc', 'c-to-c')], max_length=10)),
                ('angka', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Angka pertumbuhan (%)')),
                ('data_dasar', models.TextField(blank=True)),
                ('data_pendukung', models.TextField(blank=True)),
                ('indikator_teks', models.TextField(blank=True, verbose_name='Indikator')),
                ('narasi', models.TextField(blank=True, verbose_name='Fenomena')),
                ('fenomena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_set', to='fenomena.fenomena')),
            ],
            options={
                'verbose_name': 'Rincian Fenomena',
                'verbose_name_plural': 'Rincian Fenomena',
                'db_table': 't_fenomena_rincian',
            },
        ),
        migrations.AddConstraint(
            model_name='fenomena',
            constraint=models.UniqueConstraint(fields=('periode', 'kategori'), name='uniq_periode_kategori'),
        ),
        migrations.AddConstraint(
            model_name='fenomenaberita',
            constraint=models.UniqueConstraint(fields=('fenomena', 'berita', 'jenis'), name='uniq_fenomena_berita'),
        ),
        migrations.AddConstraint(
            model_name='fenomenarincian',
            constraint=models.UniqueConstraint(fields=('fenomena', 'jenis'), name='uniq_fenomena_jenis'),
        ),
    ]
