# Generated by Django 5.2.17 on 2026-09-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_kategori_induk'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('singkatan', models.CharField(blank=True, max_length=30)),
                ('jenis', models.CharField(choices=[('opd', 'OPD'), ('pelaku_usaha', 'Pelaku Usaha')], default='opd', max_length=20)),
                ('nama_pic', models.CharField(blank=True, max_length=100)),
                ('kontak_pic', models.CharField(blank=True, max_length=100)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('url_spreadsheet', models.URLField(blank=True, max_length=255)),
                ('id_spreadsheet', models.CharField(blank=True, help_text='Bagian alamat setelah /d/ dan sebelum /edit', max_length=100)),
                ('gid_sheet', models.CharField(blank=True, default='0', help_text='Angka setelah #gid= pada alamat spreadsheet', max_length=30, verbose_name='GID sheet')),
                ('orientasi', models.CharField(choices=[('kolom', 'Periode di kolom (indikator per baris)'), ('baris', 'Periode di baris (indikator per kolom)')], default='kolom', max_length=10)),
                ('baris_tahun', models.PositiveSmallIntegerField(blank=True, help_text='Nomor baris berisi tahun (orientasi kolom)', null=True)),
                ('baris_periode', models.PositiveSmallIntegerField(blank=True, help_text='Nomor baris berisi Triwulan I/II/III/IV (orientasi kolom)', null=True)),
                ('kolom_periode', models.PositiveSmallIntegerField(blank=True, help_text='Nomor kolom berisi I/II/III/IV (orientasi baris)', null=True)),
                ('baris_pertama', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baris_terakhir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tahun_data', models.PositiveSmallIntegerField(blank=True, help_text='Diisi bila sheet hanya memuat satu tahun', null=True)),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pengguna')),
            ],
            options={
                'verbose_name': 'OPD / Pelaku Usaha',
                'verbose_name_plural': 'OPD / Pelaku Usaha',
                'db_table': 'm_opd',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Produksi air, Volume sampah ditangani', max_length=200)),
                ('frasa', models.CharField(blank=True, help_text='Frasa untuk narasi, contoh: volume sampah yang ditangani', max_length=200)),
                ('satuan', models.CharField(blank=True, max_length=30)),
                ('sel_sumber', models.CharField(blank=True, help_text='Nomor baris bila orientasi kolom, atau nomor kolom bila orientasi baris', max_length=100, verbose_name='Nomor baris/kolom pada sheet')),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('is_aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator', to='core.kategori')),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indikator', to='inventarisasi.opd')),
            ],
            options={
                'verbose_name': 'Indikator',
                'verbose_name_plural': 'Indikator',
                'db_table': 'm_indikator',
                'ordering': ['komponen', 'opd', 'urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='NilaiIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('catatan', models.CharField(blank=True, max_length=255)),
                ('sumber_input', models.CharField(default='manual', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pengguna')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='inventarisasi.indikator')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='nilai_indikator', to='core.periode')),
            ],
            options={
                'verbose_name': 'Nilai Indikator',
                'verbose_name_plural': 'Nilai Indikator',
                'db_table': 't_nilai_indikator',
                'ordering': ['indikator', '-periode__tahun', '-periode__triwulan'],
                'constraints': [models.UniqueConstraint(fields=('indikator', 'periode'), name='uniq_indikator_periode')],
            },
        ),
    ]
