# Generated by Django 5.2.17 on 2026-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='gid_tambahan',
            field=models.CharField(blank=True, help_text='Format: gid:tahun, dipisah koma. Contoh: 1243746124:2025, 998877:2024', max_length=255, verbose_name='GID sheet tahun lain'),
        ),
    ]
