# Generated by Django 5.2.17 on 2026-09-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisasi', '0002_opd_gid_tambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='kolom_label',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nomor kolom berisi nama baris/tahun (orientasi kolom bertahun)', null=True),
        ),
        migrations.AlterField(
            model_name='opd',
            name='gid_tambahan',
            field=models.CharField(blank=True, help_text='Wajib format gid:tahun, dipisah koma. Contoh: 1243746124:2025, 998877:2024. Tahun tidak boleh dihilangkan.', max_length=255, verbose_name='GID sheet tahun lain'),
        ),
        migrations.AlterField(
            model_name='opd',
            name='orientasi',
            field=models.CharField(choices=[('kolom', 'Periode di kolom (indikator per baris)'), ('baris', 'Periode di baris (indikator per kolom)'), ('kolom_bertahun', 'Periode di kolom, tahun sebagai baris pemisah')], default='kolom', max_length=20),
        ),
    ]
