# Generated by Django 5.2.17 on 2026-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisasi', '0003_opd_kolom_label_alter_opd_gid_tambahan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opd',
            options={'ordering': ['nama'], 'verbose_name': 'Sumber Data', 'verbose_name_plural': 'Sumber Data'},
        ),
        migrations.AlterField(
            model_name='opd',
            name='jenis',
            field=models.CharField(choices=[('opd', 'OPD'), ('pelaku_usaha', 'Pelaku Usaha'), ('survei', 'Survei BPS')], default='opd', max_length=20),
        ),
    ]
